apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - minio-secret.yaml
  - minio-s3-objectstore.yaml
  - forgejo-db-credentials.yaml
  - db.yaml
  - backup.yaml
