apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - linkding-db-creds.yaml
  - minio-secret.yaml
  - minio-s3-objectstore.yaml
  # - database.yaml
  - db.yaml
  # - scheduled-backup.yaml
  - backup-schedule.yaml
