apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: botkube
resources:
  - release.yaml
  - repository.yaml

configMapGenerator:
  - name: botkube-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml
