apiVersion: v1
data:
  FORGEJO__actions__DEFAULT_ACTIONS_URL: https://data.forgejo.org
  FORGEJO__actions__ENABLED: "true"
  FORGEJO__attachment__PATH: /data/app/attachments
  FORGEJO__database__DB_TYPE: postgres
  FORGEJO__database__HOST: forgejo-db-rw:5432
  FORGEJO__database__NAME: forgejodb
  FORGEJO__database__SSL_MODE: disable
  FORGEJO__lfs__PATH: /data/lfs
  FORGEJO__log__ROOT_PATH: /data/app/log
  FORGEJO__picture__AVATAR_UPLOAD_PATH: /data/app/avatars
  FORGEJO__picture__REPOSITORY_AVATAR_UPLOAD_PATH: /data/app/repo-avatars
  FORGEJO__repository__ROOT: /data/git
  FORGEJO__security__INSTALL_LOCK: "true"
  FORGEJO__server__APP_DATA_PATH: /data/app
  FORGEJO__server__DOMAIN: forgejo.uclab.dev
  FORGEJO__server__HTTP_PORT: "3000"
  FORGEJO__server__PER_WRITE_PER_KB_TIMEOUT: "-1"
  FORGEJO__server__PER_WRITE_TIMEOUT: "-1"
  FORGEJO__server__ROOT_URL: https://forgejo.uclab.dev/
  FORGEJO__server__SSH_DOMAIN: git.uclab.dev
  FORGEJO__server__SSH_LISTEN_PORT: "2222"
  FORGEJO__server__SSH_PORT: "2222"
  FORGEJO__session__PROVIDER_CONFIG: /data/app/sessions
kind: ConfigMap
metadata:
  name: forgejo-config
  namespace: forgejo
