apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.yaml
  - configmap.yaml
  - storage-config.yaml
  - storage-data.yaml
  - deployment.yaml
  - service-http.yaml
  - service-ssh.yaml
