apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: blog
  labels:
    app.kubernetes.io/instance: blog-uclab8
    app.kubernetes.io/name: nginx
spec:
  replicas: 2 # Scale as needed!
  selector:
    matchLabels:
      app.kubernetes.io/instance: blog-uclab8
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: blog-uclab8
        app.kubernetes.io/name: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.29.4
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /www
              name: www
              readOnly: true # Nginx only reads
            - mountPath: /etc/nginx/conf.d
              name: nginx-server-block
          resources:
            requests:
              ephemeral-storage: 1Gi
            limits:
              ephemeral-storage: 2Gi
      volumes:
        - name: www
          persistentVolumeClaim:
            claimName: blog-content
            readOnly: true
        - name: nginx-server-block
          configMap:
            name: nginx-server-block
